import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import NavBar from "~/components/NavBar";
import { ClerkProvider, GoogleOneTap, SignInButton, SignedIn, SignedOut, UserButton } from "@clerk/nextjs";

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body>
        <header className="fixed">
          <SignedIn>
            <UserButton />
          </SignedIn>
        </header>
        <main>
          {children}
        </main>
        <footer>
          <NavBar></NavBar>
        </footer>
      </body>
    </html>
  </ClerkProvider>
  );
}
